import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export const ACTIVITY_START = "<!-- AUTO:ACTIVITY:START -->";
export const ACTIVITY_END = "<!-- AUTO:ACTIVITY:END -->";

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function badgeSegment(value) {
  return encodeURIComponent(String(value).replaceAll("-", "--").replaceAll("_", "__").replaceAll(" ", "_"));
}

function renderLinks(links) {
  return links.map((link) => {
    const logo = link.logo ? `&logo=${encodeURIComponent(link.logo)}&logoColor=white` : "";
    const image = `https://img.shields.io/badge/${badgeSegment(link.label)}-${badgeSegment(link.value)}-${link.color}?style=for-the-badge${logo}`;
    return `  <a href="${link.url}"><img alt="${link.label}" src="${image}"></a>`;
  }).join("\n");
}

const techBadgeStyles = {
  "Python": { logo: "python", color: "3776AB" },
  "HTML": { logo: "html5", color: "E34F26" },
  "CSS": { logo: "css3", color: "1572B6" },
  "JavaScript": { logo: "javascript", color: "F7DF1E" },
  "TypeScript": { logo: "typescript", color: "3178C6" },
  "React": { logo: "react", color: "61DAFB" },
  "Node.js": { logo: "nodedotjs", color: "339933" },
  "Git": { logo: "git", color: "F05032" },
  "GitHub": { logo: "github", color: "181717" },
  "Vercel": { logo: "vercel", color: "000000" },
  "Java": { logo: "openjdk", color: "ED8B00" },
  "C": { logo: "c", color: "A8B9CC" },
  "C++": { logo: "cplusplus", color: "00599C" },
  "SQL": { logo: "mysql", color: "4479A1" },
  "MongoDB": { logo: "mongodb", color: "47A248" },
  "Docker": { logo: "docker", color: "2496ED" },
  "Linux": { logo: "linux", color: "FCC624" },
  "VS Code": { logo: "visualstudiocode", color: "007ACC" },
  "Figma": { logo: "figma", color: "F24E1E" }
};

function renderTechStack(items) {
  return items.map((item) => {
    const style = techBadgeStyles[item];
    if (style) {
      return `<img alt="${escapeCell(item)}" src="https://img.shields.io/badge/${badgeSegment(item)}-${style.color}?style=for-the-badge&logo=${style.logo}&logoColor=white">`;
    }
    return `<img alt="${escapeCell(item)}" src="https://img.shields.io/badge/${badgeSegment(item)}-6C757D?style=for-the-badge">`;
  }).join("\n");
}

function renderFocus(focus) {
  return [
    "| Area | What I am exploring |",
    "| --- | --- |",
    ...focus.map((item) => `| **${escapeCell(item.name)}** | ${escapeCell(item.description)} |`)
  ].join("\n");
}

function renderProjects(projects) {
  return [
    "| Project | Focus | Why it matters |",
    "| --- | --- | --- |",
    ...projects.map((project) => {
      const homepage = project.homepage ? ` [Live](${project.homepage})` : "";
      return `| [**${escapeCell(project.name)}**](${project.url}) | ${escapeCell(project.focus)} | ${escapeCell(project.summary)}${homepage} |`;
    })
  ].join("\n");
}

function renderNow(items) {
  return items.map((item) => `- ${item}`).join("\n");
}

function extractActivity(readme) {
  const startIndex = readme.indexOf(ACTIVITY_START);
  const endIndex = readme.indexOf(ACTIVITY_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null;
  return readme.slice(startIndex + ACTIVITY_START.length, endIndex).trim();
}

async function readExistingActivity(readmePath) {
  try {
    const existing = await readFile(readmePath, "utf8");
    return extractActivity(existing);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

export async function generateProfileReadme({ config, manifest, readmePath }) {
  const existingActivity = await readExistingActivity(readmePath);
  const activity = existingActivity || "_Recent public activity will appear here after the workflow runs._";
  const activitySection = config.activity.enabled
    ? `\n## 📈 Recent Activity\n\n${ACTIVITY_START}\n${activity}\n${ACTIVITY_END}\n`
    : "";
  const about = config.profile.about.join("\n\n");
  const nowSection = config.now && config.now.length > 0
    ? `\n## 🔄 Now\n\n${renderNow(config.now)}\n`
    : "";
  const username = config.profile.username;

  const readme = `<!-- Generated by GitHub Profile Agent Console. Edit profile.config.json, then run npm run generate. -->
<p align="center">
  <picture>
    <source media="(max-width: 760px) and (prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.mobileDark}">
    <source media="(max-width: 760px)" srcset="./assets/hero/${manifest.assets.mobileLight}">
    <source media="(prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.desktopDark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/hero/${manifest.assets.desktopLight}">
    <img src="./assets/hero/${manifest.assets.desktopDark}" alt="${config.profile.name} - ${config.profile.headline}" width="100%">
  </picture>
</p>

<p align="center">
${renderLinks(config.links)}
</p>

## 👋 About Me

${about}
${nowSection}
## 🎯 Current Focus

${renderFocus(config.focus)}

## 💼 Featured Work

${renderProjects(config.projects)}

## 🧭 Research Direction

${config.research.narrative}

## 🛠️ Tech Stack

<p align="center">
${renderTechStack(config.techStack)}
</p>

## 📊 GitHub Stats

<div align="center">
  <img width="49%" src="https://github-readme-stats-psi-navy-76.vercel.app/api?username=${username}&show_icons=true&count_private=true&include_all_commits=true&hide_rank=true&hide_border=true&theme=tokyonight" alt="GitHub stats" />
  <img width="49%" src="https://github-readme-stats-psi-navy-76.vercel.app/api/top-langs/?username=${username}&layout=compact&langs_count=8&hide_border=true&theme=tokyonight" alt="Top languages" />
</div>

## 🏆 GitHub Trophies

<p align="center">
  <img src="https://github-profile-trophy.vercel.app/?username=${username}&theme=onestar&no-frame=false&no-bg=true&row=1&margin-w=10" alt="GitHub Trophies" />
</p>

## 🐍 Contribution Snake

<!-- Snake animation — auto-generated every 12 hours via GitHub Actions -->
<div align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/${username}/${username}/output/github-snake-dark.svg" />
    <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/${username}/${username}/output/github-snake.svg" />
    <img alt="Snake eating my contributions" src="https://raw.githubusercontent.com/${username}/${username}/output/github-snake.svg" />
  </picture>
</div>
${activitySection}
---

<p align="center">
  <img src="https://komarev.com/ghpvc/?username=${username}&style=for-the-badge&color=7C3AED&label=PROFILE+VIEWS" alt="Profile views" />
</p>

<p align="center">
  ${config.footer}
</p>
`;

  await writeFile(resolve(readmePath), readme);
  return readme;
}
